// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAFukIoPSb3z7R7qfud5fJ0cfUid9nlj0A",
    appId: "1:1012501376933:android:ba9115983a156c96f5424c",
    messagingSenderId: "1012501376933",
    projectId: "global8-6a881",
    authDomain: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'global8-6a881.appspot.com',
    measurementId: 'xxxxxxxxxxxxxxxxxxx',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAFukIoPSb3z7R7qfud5fJ0cfUid9nlj0A",
    appId: "1:1012501376933:android:ba9115983a156c96f5424c",
    messagingSenderId: "1012501376933",
    projectId: "global8-6a881",
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'global8-6a881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAFukIoPSb3z7R7qfud5fJ0cfUid9nlj0A",
    appId: "1:1012501376933:ios:b85b24831af9be4ef5424c",
    messagingSenderId: "1012501376933",
    projectId: "global8-6a881",
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'global8-6a881.appspot.com',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAFukIoPSb3z7R7qfud5fJ0cfUid9nlj0A",
    appId: "1:1012501376933:ios:b85b24831af9be4ef5424c",
    messagingSenderId: "1012501376933",
    projectId: "global8-6a881",
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'global8-6a881.appspot.com',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  );
}